[version]
current = "3.0.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''



[git]
message_template  = "Bump to {new_version}"
tag_template = "v{new_version}"


[[file]]
src = "setup.py"


[[file]]
src = "tbump/main.py"

[[hook]]
name = "Run CI"
cmd = "tools/ci.sh"

[[hook]]
name = "Check Changelog"
cmd = "grep -q {new_version} Changelog.rst"

[[hook]]
name = "Publish to pypi"
cmd = "tools/publish.sh"
