github_url = "https://github.com/dmerejkowsky/tbump"


[version]
current = "6.4.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''


[git]
message_template  = "Bump to {new_version}"
tag_template = "v{new_version}"


[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'


[[file]]
src = "tbump/cli.py"

[[before_commit]]
name = "Run CI"
cmd = "poetry run invoke lint && poetry run pytest"

[[before_commit]]
name = "Check Changelog"
cmd = "grep -q {new_version} Changelog.rst"

[[after_push]]
name = "Publish to pypi"
cmd = "tools/publish.sh"
